### ISSUE TITLE
Good Work !

### ISSUE THREAD

**Issue by mtugnoli** [NetCoreStack/Localization#10]
Hi,
How can localize a string in source section ?
How localize in DataAnnotation->ErrorMessage ?

**Comment by tahaipek** [comment]
Hi,

> How can localize a string in source section ?

Could you give a further explanation?



> How localize in DataAnnotation->ErrorMessage ?

Check this class [TestFormViewMode.cs](https://github.com/NetCoreStack/Localization/blob/master/test/NetCoreStack.Localization.Test.Hosting/Models/TestFormViewMode.cs)
For example:
`[EmailAddress(ErrorMessage = ###Localization string key on the database### )]`
`[Required(ErrorMessage =  ###Localization string key on the database### )]`

`[EmailAddress(ErrorMessage = LocalizationGlobals.DefaultLocalizationMessage.AttributeMessage.InvalidEmail)]`
`[Required(ErrorMessage = LocalizationGlobals.DefaultLocalizationMessage.AttributeMessage.Required)]`

**Comment by mtugnoli** [comment]
public IActionResult About()
{
	ViewData["Message"] = "How localize this ?";

	return View();
}

**Comment by tahaipek** [comment]
```
public class HomeController : Controller
{
        private readonly IStringLocalizer _stringLocalizer;
        public HomeController(IStringLocalizer stringLocalizer)
        {
            _stringLocalizer = stringLocalizer;
        }

        public IActionResult About()
        {
            ViewData["Message"] = _stringLocalizer["Hello"];

            return View();
        }
}
```

Check this [row](https://github.com/NetCoreStack/Localization/blob/master/src/NetCoreStack.Localization/ServiceCollectionExtensions.cs#L38)
```services.AddScoped<IStringLocalizer, DatabaseStringLocalizer>();```

**Comment by mtugnoli** [comment]
Very good !
