### ISSUE TITLE
_stringLocalizer with null values

### ISSUE THREAD

**Issue by jigarce** [NetCoreStack/Localization#12]
Hi Again,

I am having one small issue with NULL values .

Do you have any code which automatically check if there is null value anywhere while converting values with localize value  if there is a NULL it should skip converting that .

Regards,
jigar

**Comment by tahaipek** [comment]
Hi @jigarce 

I have good news for you.

I've finished developing the feature you want and added the **"LocalizationSettings.UseDefaultLanguageWhenValueIsNull"** property to the AppSettings.json file. Can you check the **readme.md** and **DataBase_TestProjectResources_Script.sql (row: 38)** file again?

Also thanks to this request, i have solved the logic error on client-side.

Check this commit. https://github.com/NetCoreStack/Localization/commit/4f0b70d38c5e823607a92d4c80d283f0552d44c2

**Comment by jigarce** [comment]
Oh , Great man!
I will see and get back to you!
Regards,
jigar
